# Generated by Django 5.2.7 on 2025-11-03 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Destination Name"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Country"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Destination",
                "verbose_name_plural": "Destinations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Language Name"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="ISO 639-1 language code (e.g., 'en', 'es', 'fr')",
                        max_length=10,
                        unique=True,
                        verbose_name="Language Code",
                    ),
                ),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Speciality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Speciality Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Speciality",
                "verbose_name_plural": "Specialities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Guide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guide_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for the guide",
                        max_length=50,
                        unique=True,
                        verbose_name="Guide ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the guide",
                        max_length=200,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description about the guide's experience and background",
                        verbose_name="Description",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average rating out of 5.0",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                (
                    "rate_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Daily rate in your currency",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Rate per Day",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the guide is currently accepting bookings",
                        verbose_name="Available",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destinations",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Locations where the guide provides services",
                        related_name="guides",
                        to="guide.destination",
                        verbose_name="Destinations",
                    ),
                ),
                (
                    "languages",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Languages spoken by the guide",
                        related_name="guides",
                        to="guide.language",
                        verbose_name="Languages",
                    ),
                ),
                (
                    "specialities",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Guide's areas of expertise",
                        related_name="guides",
                        to="guide.speciality",
                        verbose_name="Specialities",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guide",
                "verbose_name_plural": "Guides",
                "ordering": ["-rating", "name"],
            },
        ),
    ]
