# Generated by Django 5.2.7 on 2025-11-03 15:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("guide", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "package_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("destination", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("duration_days", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Packages",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "booking_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("travel_date", models.DateField()),
                ("number_of_people", models.PositiveIntegerField(default=1)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "guide_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fee charged for the guide service",
                        max_digits=10,
                        null=True,
                        verbose_name="Guide Fee",
                    ),
                ),
                (
                    "guide_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Customer rating for the guide (0-5)",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                        verbose_name="Guide Rating",
                    ),
                ),
                (
                    "guide_review",
                    models.TextField(
                        blank=True,
                        help_text="Customer review/feedback for the guide",
                        verbose_name="Guide Review",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("special_requests", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guide",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="guide.guide",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Bookings",
                "ordering": ["-created_at"],
            },
        ),
    ]
